version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  shell:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - api

  investments-mfe:
    build: ./projects/investments-mfe
    ports:
      - "4201:80"
    depends_on:
      - api